### ISSUE TITLE
P^n or P_n for polynomial space

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#129]
We use P^n at least once for the polynomial vector space of degree n. Since this is (n+1)-dimensional and X^n often denotes a product of spaces X, maybe P_n is more appropriate. (I don't have an LA text handy at the moment, but Wikipedia at least uses P_n.)

**Comment by siwelwerd** [comment]
Hopefully we use it every time 🙃. The choice was intentional at some point long ago (perhaps to match a certain textbook), but may no longer be relevant -- I honestly can't remember.

**Comment by StevenClontz** [comment]
I don't recall the logic either, but searching the net reveals a lot of \(P_n\)s and not a lot (or any) of \(P^n\)s, so while I'm porting things I'll update this, if that's okay with you.
