### ISSUE TITLE
PTX: Port application-focused projects

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#134]

**Comment by siwelwerd** [comment]
@StevenClontz Is this on your radar to be done in the next two weeks?

**Comment by StevenClontz** [comment]
It wasn't but if it's a blocker I can carve out the time

**Comment by siwelwerd** [comment]
I didn't have time for any applications last semester because we lost so many days to COVID + hurricanes. But this semester I am on track to have the last week of classes (Apr 26-30) to spend on applications, so it would be nice if these were in the pretext slideshow.

**Comment by StevenClontz** [comment]
Sure - all of them or do you have any priorities?


Steven Clontz
https://clontz.org - ***@***.***

**Comment by siwelwerd** [comment]
The PageRank one and the geology one are probably the only two I'll have time for. The other two could wait.

**Comment by StevenClontz** [comment]
https://teambasedinquirylearning.github.io/linear-algebra/applications.html is now a thing, leaving this issue open until the others are ported.

(The slides look pretty ratty though but are functional I think.)

**Comment by siwelwerd** [comment]
Yeah, should work for my purposes, thanks.  There is something screwy with the sectioning though, https://teambasedinquirylearning.github.io/linear-algebra/geology.html sends you to the PageRank section.

**Comment by StevenClontz** [comment]
Whoops that's fixed in source at 2ad3e58fd - rebuilding now...


Steven Clontz
https://clontz.org - ***@***.***

**Comment by StevenClontz** [comment]
https://teambasedinquirylearning.github.io/linear-algebra/truss.html is now live*

@sharonakrinsky and @siwelwerd should put eyeballs on it to make sure I didn't mess anything up.

* The quick turnaround is courtesy productive procrastination from other stuff lol

**Comment by sharonakrinsky** [comment]
> https://teambasedinquirylearning.github.io/linear-algebra/truss.html is now live*
> 
> @sharonakrinsky and @siwelwerd should put eyeballs on it to make sure I didn't mess anything up.
> 
> * The quick turnaround is courtesy productive procrastination from other stuff lol

I love it! Productive procrastination!!! It looks good at a first glance.

**Comment by sharonakrinsky** [comment]
Also - I just posted two issues on the other applications
