### ISSUE TITLE
Rename repo to linear-algebra?

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#136]
Since we're now organized in the TeamBasedInquiryLearning organization, renaming the repo to `linear-algebra` would host our site at https://teambasedinquirylearning.github.io/linear-algebra/ and be a bit more recognizable at a glance.

**Comment by siwelwerd** [comment]
Concur

**Comment by StevenClontz** [comment]
Done. The old website URL will break but it's only really been shared in one twitter post which I'll reply to now.

**Comment by StevenClontz** [comment]
Git refs should be updated but it's non-essential as GitHub redirects well in general.

**Comment by siwelwerd** [comment]
Good thing I learned how to do that last week. Too bad I already forgot 🙃
