### ISSUE TITLE
Definition of "binary operation" in V1

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#142]
So @crgibbons pointed out that we are implicitly using a definition of "binary operation" as a map VxV \rightarrow V, and that this may not be standard. This gets a little confusing when we define subspaces as "Smaller vector spaces within bigger vector spaces" -- if the image of the binary operation is not required to be the vector space, you don't necessarily get closure.

As we convert to PreTeXt, it might be nice to have an aside where we can point this out (though we probably still don't want this in the slides).

**Comment by siwelwerd** [comment]
Another good aside comment would be how in our definition of subspace, the operations must be the same as those of the larger vector space.  Does pretext have a <subtle-but-important-technical-note> tag?

**Comment by StevenClontz** [comment]
<aside/> is the appropriate element for this, I believe.


Steven Clontz
https://clontz.org - steven.clontz@gmail.com

**Comment by siwelwerd** [comment]
That will make it easy. Does the PreTeXt slide generation allow you to decide which tags turn into slides? So that we could just omit all <aside>?

**Comment by StevenClontz** [comment]
More or less. There's code (that I need to refactor for the IUSE project) that takes a PreTeXt book, extracts the desired elements, and spits out PreTeXt slideshow source code, which then can be built into Reveal.JS slides (and some limited Beamer support, but Reveal.JS is much nicer).
