### ISSUE TITLE
PTX: Videos

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#143]
Because of the pandemic, I have created videos aligned with each standard. These could be included into the PreTeXt version. The videos are currently in Panopto, so either they will have to be transferred to YouTube, or PreTeXt will need to offer support for Panopto.

(See discussion here https://twitter.com/siwelwerd/status/1326694815808057345 )

**Comment by siwelwerd** [comment]
The following code should do the trick. Panopto will give you a link to a podcast, and you can download captions separately.

`<figure>
	<video xml:id="video-E1" source="https://southalabama.hosted.panopto.com/Panopto/Podcast/StreamInBrowser/b9e50548-7fcd-42a9-a91e-ac190138c4b7.mp4?mediaTargetType=videoPodcast">
		<track kind="subtitles" label="US English" xml:lang="en" source="videos/E1-captions.vtt" default="yes"/>
	</video>
	<caption>Video example: Converting between systems, vector equations, and augmented matrices</caption>
</figure>`

Question for @StevenClontz : Are we okay hosting the videos through Panopto, or is it better to download them and include them as part of the repository (I have to do that with the captions anyways)?

**Comment by StevenClontz** [comment]
Putting large video files in a Git repo is a bad idea (I'm not even sure GitHub would accept them). For now let's do less work and use Panopto hosting, but we'll probably want a TBIL video channel on YouTube if our cohorts develop video materials as well.

**Comment by siwelwerd** [comment]
They are not super large because I have kept them short (the one in the example above is 25MB). But yes, I envision our TBIL fellows re-recording and improving some (or all) of them, so I am happy to leave them in Panopto for now.

**Comment by siwelwerd** [comment]
Extra wrinkle: the link from Panopto no longer works if you are not logged in. However, if you change "StreamInBrowser" folder to "Social", it seems to work.

However, this suggests Panopto may be more fragile than I originally thought. I think we should roll with it for the moment, but think hard about shifting elsewhere in the future. Maybe a TBIL Youtube channel should be part of the grant work.

**Comment by StevenClontz** [comment]
> Extra wrinkle: the link from Panopto no longer works if you are not logged in. However, if you change "StreamInBrowser" folder to "Social", it seems to work.

Wow that's real amateur hour stuff from Panopto.

While there are many things wrong with YouTube platform, there's a reason it's the go-to. Vimeo would be the next-best option, but either we need money to use it, or we need to stay within the constraints of their "Vimeo Basic" free tier (which I don't know if we would).

I agree that Panopto is the choice for this spring however.
