### ISSUE TITLE
Update readme & deprecate LaTeX

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#145]
The readme needs to be updated to reflect our use of PreTeXt. Perhaps in conjunction with completing milestone:2021-spring , we should also deprecate the LaTeX version.

**Comment by StevenClontz** [comment]
Part of this work should include moving the `ptx` source into the base of the repo, and all deprecated materials like `tex`/`pdf` into a `deprecated` directory temporarily, until they are fully represented in maintained sections of the source (at which point they can be deleted).

**Comment by StevenClontz** [comment]
Closed by a88169086167b07c4a43da0b2f02b7daa5f45684
