### ISSUE TITLE
PTX: Get LaTeX/PDF build working

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#146]

**Comment by siwelwerd** [comment]
I managed to fix the commutative diagram issue (in the HTML version at least), but I am not 100% sure it won't cause issues in the LaTeX/PDF generation. So let's be sure to double check Figure 4.1.2 when implementing this.

https://github.com/TeamBasedInquiryLearning/linear-algebra/issues/133#issuecomment-759738664
