### ISSUE TITLE
Replace \circledText with semantic \pivot

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#147]
Right now, \circledText appears as a box in LaTeX builds, because reasons #133 

So we should make the command `\pivot` that doesn't care about its presentation in various contexts.

**Comment by siwelwerd** [comment]
Also, it does not appear to provide any decoration in the slides.

**Comment by StevenClontz** [comment]
Yikes that's a bigger issue. I'll look into it

**Comment by siwelwerd** [comment]
I saw some other weird things going on in the slides, and then I hit refresh and fixed them, as well as the pivot in the slides. So maybe this was just some weird caching thing going on on my end.
