### ISSUE TITLE
PTX: Slides

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#148]

**Comment by StevenClontz** [comment]
This is 90% implemented in e2c4ac5 using the `xsltproc` command-line since neither the book-to-slideshow nor slides-to-html conversions= is supported by PreTeXt-CLI yet. Once all the tikz/etc updates are merged into main, I'll update the build documentation to also build slides, and get this merged into main as well.

A handful of items will need to be redesigned to fit well in a slide. But as a stop-gap measure, instructors can resize their browser zoom to get everything in the viewport.

**Comment by siwelwerd** [comment]
All the blocking issues are now closed. We can publish the HTML to docs now, and you can produce the slides. If you leave some more detailed instructions on generating them here, I can proofread and try to fix any issues with the slides next week.

**Comment by StevenClontz** [comment]
I've got this merged into `main`, and I went ahead and edited Chapter 1/E to be (what I think is) well-presented in both the book and slideshow formats. Info for building slides is now in the README; access to `xsltproc` on the command-line is assumed (I can make a Python version if this is a problem).

Leaving this open until @siwelwerd reviews the rest of the slides.

**Comment by siwelwerd** [comment]
Is there a way to get a table of contents into the slideshow?  Looks like right now, if I am doing module G I have to open the slide show, and then arrow over 20 or 30 times to get to the section I need.

**Comment by StevenClontz** [comment]
It's non-trivial (unless there's a slick Reveal.js feature I can take advantage of maybe) but technically possible. I've opened #160, but for the immediate future you'll need to arrow over. (Something to do while MathJax crunches through all the typesetting it has to do...)

**Comment by siwelwerd** [comment]
The good news is it's not as big a deal at the beginning :)

**Comment by StevenClontz** [comment]
This is also kind of the reverse of #157 - the *best* (and potentially easiest) solution would be to somehow support slideshow URLs like https://teambasedinquirylearning.github.io/linear-algebra/slides.html#/E1 for https://teambasedinquirylearning.github.io/linear-algebra/E1.html but that relies on features of Reveal.js that may or may not exist.

**Comment by siwelwerd** [comment]
I think the `<sidebyside>` tag is not being handled well, and am not sure where to fix it.  See here for example:
<img width="941" alt="Screenshot 2021-01-27 144744" src="https://user-images.githubusercontent.com/30658947/106052330-0edf7180-60af-11eb-828a-30edc301f652.png">

**Comment by StevenClontz** [comment]
Yeah. It's not pretty but it's functional at the moment. I'll need to research if the fix is our book-to-slideshow export, or the upstream slideshow-to-revealjs implementation.

**Comment by siwelwerd** [comment]
I believe it is the latter, because the '<sidebyside>' tag does get copied over into the slides/slides.ptx file, so the slides/extract-slides.xsl appears to be handling it correctly.

**Comment by StevenClontz** [comment]
Let me know if this need to be addressed sooner, but right now this is looking like a summer project for me.

**Comment by siwelwerd** [comment]
Looks like `<sidebyside>` is only used in module E, so this is definitely low on the priority list.

`drew@LAPTOP-AU26PJ5K:~/tbil-la$ grep sidebyside source/*/*ptx
source/01-E/01.ptx:    <sidebyside widths="33% 33% 33%" margins="auto" valign="middle">
source/01-E/01.ptx:    </sidebyside>
source/01-E/01.ptx:        <sidebyside widths="33% 33% 33%" margins="auto" valign="middle">
source/01-E/01.ptx:        </sidebyside>
source/01-E/01.ptx:        <sidebyside widths="49% 49%" margins="auto" valign="middle">
source/01-E/01.ptx:        </sidebyside>
source/01-E/02.ptx:  <sidebyside widths="50% 50%">
source/01-E/02.ptx:  </sidebyside>
source/01-E/02.ptx:      <sidebyside widths="33% 33% 33%">
source/01-E/02.ptx:        </sidebyside>
source/01-E/02.ptx:      <sidebyside widths="33% 33% 33%">
source/01-E/02.ptx:        </sidebyside>
source/01-E/02.ptx:      <sidebyside widths="33% 33% 33%">
source/01-E/02.ptx:        </sidebyside>
source/01-E/02.ptx:      <sidebyside widths="33% 33% 33%">
source/01-E/02.ptx:</sidebyside>`

**Comment by siwelwerd** [comment]
Closed by #255
