### ISSUE TITLE
PTX Implement sage cells

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#151]
I think it would be handy to have small sage cells after many of the activities to make it easy for students to find the RREF (or any other computation they need), without the congitive load of shifting focus elsewhere.

**Comment by StevenClontz** [comment]
I was also thinking this. Are we imagining a workflow where students have the textbook pulled up, and instructors have slides?

It's worth noting that I have code in https://github.com/StevenClontz/mathematics-of-data to build CoCalc-compatible Jupyter notebooks on PreTeXt documents organized in a certain way (which includes this one). Essentially that's redundant with Sage cells, except it costs money but allows saving of work.

**Comment by StevenClontz** [comment]
I think https://twitter.com/SeanFitzMath did some work implementing Sage cells in slideshows, but that strikes me as a bit finnicky (without putting too much thought into the idea).

**Comment by siwelwerd** [comment]
Yeah, the book is more compact, so I can see students pulling that up on their own devices in class (definitely they will in a synchronous online class). But this would also better support someone who wanted to do asynchronous online, which Tien is doing this semester, as well as other individual uses (such as reviewing before an assessment). I don't see the cells in the slideshows themselves as adding a ton of value. 

By the way, sage cells embedded into CheckIt might be handy as well. Just in case you need another feature to implement in all of your free time 🙃

**Comment by StevenClontz** [comment]
> By the way, sage cells embedded into CheckIt might be handy as well. Just in case you need another feature to implement in all of your free time 🙃

https://github.com/StevenClontz/checkit/issues/21
