### ISSUE TITLE
Table of Contents slide

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#160]
Investigate adding quick links below the initial slide to access certain chapters/sections without scrolling through.

**Comment by siwelwerd** [comment]
Possible workaround: A slideshow of just one module/chapter, rather than the whole course.  Would `xsltproc --xinclude -o slides/slidesE.ptx slides/extract-slides.xsl source/01-E/main.ptx` do what I think it will?

**Comment by StevenClontz** [comment]
It won't, but something similar could be rigged.

**Comment by siwelwerd** [comment]
Is this resolved by the existence of https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/7535ade94eb678b30a2f4d896e7f5a506b831314/source/meta/slideshow.ptx ?  If so, this can be closed.
