### ISSUE TITLE
Tikz

### ISSUE THREAD

**Issue by TienChih** [TeamBasedInquiryLearning/linear-algebra#161]
Hi Friends,

I could be wrong, but I do believe there's supposed to be tikz pictures on some of these pages like this one: https://teambasedinquirylearning.github.io/linear-algebra/V3.html

Thanks!

Tien

**Comment by StevenClontz** [comment]
I rebuilt the HTML with diagrams. There's some weird caching on that link but it should work in the near future (I see the file here https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/main/docs/images/image-1.svg ).

@siwelwerd I updated our README to include a one-liner that also rebuilds diagrams for when that's necessary.

**Comment by StevenClontz** [comment]
Ah... https://webmasters.stackexchange.com/a/118928

> GitHub Pages by default places a caching header of 10 minutes on all resources

So check in 10 min?

**Comment by StevenClontz** [comment]
Still broken. Definitely a caching issue as https://teambasedinquirylearning.github.io/linear-algebra/images/image-1.svg?foo works while https://teambasedinquirylearning.github.io/linear-algebra/images/image-1.svg doesn't. So I may need to rebuild/redeploy to ping gh-pages to uncache the 404d image. I'll do that tomorrow if it doesn't fix itself.

**Comment by siwelwerd** [comment]
Appears to be working to me?

**Comment by StevenClontz** [comment]
Then it's specific to my IP or something. I"ll close this.
