### ISSUE TITLE
Missing time estimates on student activities

### ISSUE THREAD

**Issue by sharonakrinsky** [TeamBasedInquiryLearning/linear-algebra#164]
It would be great to get back the time estimates (I'm picking them up from the previous facilitator notes right now).

**Comment by siwelwerd** [comment]
The estimates are within the PreTeXt source, but are currently not used in the output (HTML or slides)

**Comment by StevenClontz** [comment]
I'm asking here https://groups.google.com/g/pretext-support/c/oXYF1YDIiEY if there's a good way to express this information in PreTeXt before I go about writing a custom solution.

**Comment by siwelwerd** [comment]
Might be worth thinking about #80 at the same time?

https://github.com/TeamBasedInquiryLearning/linear-algebra/issues/80#issuecomment-367384362

**Comment by StevenClontz** [comment]
Based on discussion it seems adding an @estimated-time attribute to PreTeXt has support.  Showing the # of tasks on slides when estimated time is configured to be shown seems reasonable.
