### ISSUE TITLE
Typographical: e.g. \vec{v_n} instead of \vec{v}_n

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#166]
Quick guess -- \vec{v_n} instead of \vec{v}_n? Noting here to fix later.

<img width="931" alt="Screenshot 2021-02-12 084337" src="https://user-images.githubusercontent.com/30658947/107782312-8566ab00-6d0e-11eb-82e3-b9369eeada39.png">

**Comment by StevenClontz** [comment]
Agree on guess
