### ISSUE TITLE
Merge M3&M4?

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#172]
In our recent meeting it was brought up that checking invertibility and computing inverses might be appropriately combined into the same outcome.

**Comment by siwelwerd** [comment]
Yeah, we have gone back and forth on this previously. The counterpoint was that having them separate leaves a couple of "easy wins" later in the semester for students. I think it might be good to leave this issue open for the time being, and let the TBIL fellows make the call this summer.

**Comment by siwelwerd** [comment]
Thought: add a standard (or part of a standard) with a prompt like: Suppose T: R^3 --> R^3 is an invertible linear transformation such that T(1 2 3) = [1 1 1] and T(4 5 6) = [-3 0 -2]; compute T^{-1} ( -2 1 -1).   I don't think this can be done via calculator.
