### ISSUE TITLE
Images disappearing

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#173]
99% sure this is just a documentation issue. But in @StevenClontz's most recent commit, he introduced some new diagrams (in the pagerank section). I ran a git pull, made a minor change elsewhere, and published the change, and it looks like this deleted the diagrams. Because I didn't change or add any diagrams, I just ran 'pretext build' instead of 'pretext build -d'

Now that I think about it, the images should have been pulled down when I ran git pull; is the 'pretext publish' command deleting things?

**Comment by siwelwerd** [comment]
Ah, okay, see here:

https://github.com/PreTeXtBook/pretext-cli/blob/516a2e4e3950bb73214bfa0639b4db23f84436b2/pretext/cli.py#L225

The 'pretext publish' command deletes the docs folder. When you build new diagrams, they are created in the ignored source/output/html/images, and 'pretext publish' copies them to docs/images .  But when I run 'pretext publish', it deletes docs/images, and then since I haven't built the images into source/output/html/images, they can't be copied over to docs/images.

Workaround is obviously for each author to rebuild diagrams, but this takes a long time, and obviously I don't know after a git pull if another commit has introduced new images or not.

This is probably related to https://github.com/PreTeXtBook/pretext-cli/issues/65 .

**Comment by StevenClontz** [comment]
Thanks for the detective work. Yeah, for now make sure you rebuild images
regularly, but we'll leave this open so I can make sure it's part of our
work this summer improving the CLI workflow (generally, and in particular
for our Fellows).


Steven Clontz
https://clontz.org - ***@***.***

**Comment by siwelwerd** [comment]
I see the pretext CLI gives a warning message now, so closing this.
