### ISSUE TITLE
Slide issue with appendix slide for Observation A.2.2

### ISSUE THREAD

**Issue by sharonakrinsky** [TeamBasedInquiryLearning/linear-algebra#177]
The slide is repeating the title. "The $978,000,000,000 IdeaThe $978,000,000,000 Idea"

**Comment by siwelwerd** [comment]
I think this is an upstream issue with PreTeXt slide generation. It does not appear to be handling the `<title>` correctly inside of an `<observation>`

**Comment by siwelwerd** [comment]
This appears resolved (perhaps by something upstream in PreTeXt), so closing this.
