### ISSUE TITLE
Fact 2.4.3

### ISSUE THREAD

**Issue by StevenGubkin** [TeamBasedInquiryLearning/linear-algebra#182]
"Any subset  of a vector space  that contains the additive identity satisfies the eight vector space properties automatically, since it is a collection of known vectors."

I don't think this sentence makes sense.  If any subset satisfied the axioms, then wouldn't any subset be a subspace?  I think just removing this sentence would be a fine fix.  It would require a slight tweak of the next sentence.

**Comment by siwelwerd** [comment]
This is related to #142 , in that the key subtlety is what is the codomain of the operations. So we need to make this more clear here as well.
