### ISSUE TITLE
Move answers/solutions to <answer>/<solution>?

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#184]
Often we have "observation" that's spelling out an answer. To tuck those away in the textbook and avoid spoiling insights for students, we should mark them up as <answer>/<solution> environments. (And then, I need to extract those as slides for presentation.)

**Comment by siwelwerd** [comment]
Does PreTeXt have a `<spoiler>` tag or attribute?

**Comment by StevenClontz** [comment]
`<commentary>` only shows up when asked for (right now, when we do `subset` builds, but long-term we could have an instructor version that's less publicized than the main version).

**Comment by StevenClontz** [comment]
https://groups.google.com/g/pretext-dev/c/UeZJff9uwn4 allows for tagging more arbitrary things to only appear in specific version builds.
