### ISSUE TITLE
Convert videos to YouTube

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#186]
Currently videos in the textbook are in Panopto, which changed how they do things and broke all of the links. To prevent this from happening again, the videos need to be uploaded to YouTube and the links here updated.

**Comment by StevenClontz** [comment]
Channel is up here: https://www.youtube.com/channel/UCvTIG_smKGALUZL0KWRVFWg/

Drew send me (elsewhere) your non-South Google account info so I can add you as a manager.

**Comment by StevenClontz** [comment]
Videos are up there now. I haven't wired them up to the book yet; as a stop-gap I'll first link to the playlist https://www.youtube.com/watch?v=kpOK7RhFEiQ&list=PLwXCBkIf7xBMo3zMnD7WVt39rANLlSdmj in the frontmatter somewhere.

**Comment by StevenClontz** [comment]
This is done in https://stevenclontz.github.io/linear-algebra-tbil-2021/ - to be honest, I'm not going to rush to fix things here upstream until we get a request for it since everyone I know is using that in-development version this fall. Once that's merged here this will be closed in any case.
