### ISSUE TITLE
establish reasoning for infinitely-many solutions in LE3

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#187]
I think we've set up students to make clear arguments for 0 and 1 solutions in LE3, but we may want to make some sort of "less variables than non-trivial equations" argument for why you get infinitely-many solutions otherwise.

**Comment by siwelwerd** [comment]
Also thinking the checkit problems might need some more variety in their shapes.  Seeing a few students try to infer that a row of 0=0 implies infinitely many solutions (which is a fair pattern match to the existing check-it problems, but not true in general)

**Comment by StevenClontz** [comment]
Agreed - easy solution there is to ensure 0=0 appears in every assessed example.
