### ISSUE TITLE
CheckIt import into Brightspace (D2L)

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/linear-algebra#193]
When a problem database is generated from CheckIt to import into Brightspace, the LaTeX code for $\middle|$ does not properly render.
![middle](https://user-images.githubusercontent.com/91138060/159004454-72465846-1010-4f71-835d-c02e9c8b16ff.JPG)

It shows up with the actual "\middle|". This appears in AT3 problems for image and kernel, but there are other places that \middle| also shows up, maybe back in LE4. Not sure of the fix.

**Comment by StevenClontz** [comment]
moved to checkit repo
