### ISSUE TITLE
Checkit Import into Brightspace (D2L)

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/linear-algebra#194]
When importing the problem database from CheckIt into Brightspace, the subscript numbering on VS9 tends to loop after three occurrences. So x_4 shows up as x_1, x_5 shows up as x_2, etc. Sample below.
![vs9](https://user-images.githubusercontent.com/91138060/159004755-58db1b1d-d3cb-45bd-9de0-1dd259514f23.JPG)

I think the pattern is that for three or fewer variables, things are OK, but whenever there are more than three, the looping happens.

**Comment by StevenClontz** [comment]
This is a more general bug (that happens only *sometimes* and we're not sure why). I'm hoping it comes out in the wash of an update to 0.2 but will investigate further if not. 

https://github.com/TeamBasedInquiryLearning/checkit-tbil-la/issues/37
