### ISSUE TITLE
Application slides not generated

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#201]
For all three sections of applications, the slide generation appears to have only produced the title slide.

Example: https://teambasedinquirylearning.github.io/linear-algebra/2022/truss.slides.html

This should be fixed in the live 2022 edition.

**Comment by StevenClontz** [comment]
Closed in [18df6d9](https://github.com/TeamBasedInquiryLearning/linear-algebra/commit/18df6d95e9a5ecb80a18c3617e99970cd97e4f90)

**Comment by StevenClontz** [comment]
(actual solution was at 24caaffe1b9b4e59941f2c5c9f0a6ae7774a4dc4 )
