### ISSUE TITLE
Pretext CLI warning

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#210]
I get this message when running pretext
```warning: Using CLI version 1.1.0 but project's `requirements.txt`
warning: is configured to use 1.0.5. Consider either installing
warning: CLI version 1.0.5 or changing `requirements.txt` to match 1.1.0.```

I am assuming that it is because we have `==` in
https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/d153a68667aa2abd39f075b73008ebbeaecfed7d/requirements.txt#L1

Can we change this to `>=`?

**Comment by StevenClontz** [comment]
I'm expecting 1.2.2 to be out soon, and it comes with a graphical upgrade. I'll bump the version then.

To answer your question though: that's legal for Pip, but not PreTeXt-CLI: we want to know the exact version for debugging purposes.
