### ISSUE TITLE
VS1 Exercise incorrect prompt

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#213]
Reported by Jordan Kostiuk: The first published exercise in the Checkit Library asks students to show that a false property (scalar multiplication distributes over vector addition).

I believe this is Case 1 here: 
https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/57969eb0403ff7d2f5cf960a255d4ed7eb283e8d/exercises/outcomes/VS/VS1/generator.sage#L38

**Comment by siwelwerd** [comment]
I think this is fixed now, but needs to be rolled out to checkit.clontz.org

**Comment by StevenClontz** [comment]
Fixed at https://teambasedinquirylearning.github.io/linear-algebra/2023/exercises/#/bank/VS1/1/
