### ISSUE TITLE
AT4 Exercise Bank

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#216]
We need some deeper questions that probe at connections between injectivity/surjectivity and other vector properties.

**Comment by siwelwerd** [comment]
The assessment questions or the activities?

**Comment by StevenClontz** [comment]
Exercise bank - right now we don't have the nice scaffolding we added for other exercises that prompts students to consider more than pivot rows and columns.

**Comment by StevenClontz** [comment]
I may have overdone it...

![image](https://user-images.githubusercontent.com/1559632/236337339-e246b195-5397-437e-ae7c-7e851f6a3fad.png)

![image](https://user-images.githubusercontent.com/1559632/236337364-a28d8f94-cd07-4a6b-a6e3-9c261b891998.png)

![image](https://user-images.githubusercontent.com/1559632/236337381-973bf040-719e-407b-982b-6ba05dcf20a8.png)

![image](https://user-images.githubusercontent.com/1559632/236337295-2dae3e1b-13c9-4379-8c34-959870b2093f.png)

But I keep seeing students who breeze through this and don't have all the possibilities straight, so maybe it's worth the time...?

**Comment by StevenClontz** [comment]
In a more recent commit, I simplified the subtasks to just 3 (but there are still 4 main tasks):

![image](https://github.com/TeamBasedInquiryLearning/linear-algebra/assets/1559632/8ad7326e-9eca-415d-9cf5-f2a1b2ff1036)

https://teambasedinquirylearning.github.io/linear-algebra/2023/exercises/#/bank/AT4/1/

**Comment by siwelwerd** [comment]
I don't understand why they need to do four of these if they give a good explanation in the first subtask.

**Comment by siwelwerd** [comment]
If you really want them to do 4 things, split out subtask 2 to do four times.  But subtask 1 is the same for all four, and subtask 3 (essentially a vocabulary recall question) is the same for all four as well.

**Comment by StevenClontz** [comment]
> I don't understand why they need to do four of these if they give a good explanation in the first subtask.

It's because they don't give good explanations, and it's easier to explain to the student why it's an insufficient explanation if I can point to specific examples on the quiz itself where the explanation breaks down.

I really like your idea to have a common task 1&3 with task 2 have four subtasks for different matrices.

**Comment by StevenClontz** [comment]
Getting ready to do things "right* for this project and using PRs... https://github.com/TeamBasedInquiryLearning/linear-algebra/pull/222

![image](https://github.com/TeamBasedInquiryLearning/linear-algebra/assets/1559632/fbf4547a-a27c-4bd0-9cbd-d5346a2599f6)

![image](https://github.com/TeamBasedInquiryLearning/linear-algebra/assets/1559632/01a69140-b21f-4752-9ddc-6b669fb74649)

![image](https://github.com/TeamBasedInquiryLearning/linear-algebra/assets/1559632/cebe1db8-a9d4-446d-b694-ab173eeba92d)

Is this an okay balance?

**Comment by StevenClontz** [comment]
(Someone who felt the problem was too long could edit the template to give the RREF for each part.)

**Comment by siwelwerd** [comment]
My gut says 4 is still too many (maybe 2 or 3  subparts on task 2 suffice), but you taught this more recently, so this seems worth testing with students.

**Comment by StevenClontz** [comment]
Since I'm teaching in the fall, I'm going to leave it with 4, and will adjust if I get feedback or notice it's running long.

**Comment by StevenClontz** [comment]
Closed by #222
