### ISSUE TITLE
Less tedious AT5 (former VS1) checkit exercises

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#218]
I'm getting a lot of this

![image](https://user-images.githubusercontent.com/1559632/235479320-40775abc-879e-460b-b1b4-575fe5f8c7fb.png)

I think we can keep things nice and varied without having quite so much tedium in the verification. (Or I might start teaching how to use a CAS along with this outcome - I'm not having a lot of fun grading these either!)

**Comment by StevenClontz** [comment]
Also the final answers could include the algebraic simplification of both sides of the identity in task 1, which would simplify verification of answers by both students and instructors.

**Comment by StevenClontz** [comment]
> Also the final answers could include the algebraic simplification of both sides of the identity in task 1, which would simplify verification of answers by both students and instructors.

This is done in 4ce9c1d051 along with a reimplementation of the templating/generation. But for now the logic (which I only have a vague guess as to how @siwelwerd designed it) for generating operations remains unchanged, which means we still have a few stinkers that are significantly more tedious than the others.

**Comment by siwelwerd** [comment]
Do you have some examples of generated problems that are extra tedious?

**Comment by StevenClontz** [comment]
https://teambasedinquirylearning.github.io/linear-algebra/2023/exercises/#/bank/AT5/19/ (link will be live in a moment)

![image](https://user-images.githubusercontent.com/1559632/236574887-39a89190-f7a6-4aec-b19b-dc1bed98eecb.png)

**Comment by siwelwerd** [comment]
That looks like its from this case.  Are there others from other cases? (Just trying to narrow down what to fix here)

https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/4ce9c1d05161c8cfac10199494d7e643f380087e/exercises/outcomes/AT/AT5/generator.sage#L57

**Comment by StevenClontz** [comment]
I think that might be the main culprit. That multiplication ends up so ugly I think I'd be okay limiting its questions to just verifying multiplicative identity.

**Comment by siwelwerd** [comment]
I'll play around with it next week. Maybe limiting the exponents to squares will make things more manageable as well.
