### ISSUE TITLE
Improve clarity in EV5

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#257]
- In [Activity 2.5.6](https://teambasedinquirylearning.github.io/linear-algebra/2023/EV5.html#activity-53) and maybe elsewhere, the k hat is typeset differently than i hat and j hat.
- In [Activity 2.5.8](https://teambasedinquirylearning.github.io/linear-algebra/2023/EV5.html#activity-54) the phrasing in answer choice (d) is unclear.
- In [Activity 2.5.8](https://teambasedinquirylearning.github.io/linear-algebra/2023/EV5.html#activity-54) and maybe elsewhere, it is unclear to say a set "fails to span" -- here it should say "fails to span \mathbb{R}^4".

**Comment by StevenClontz** [comment]
> In [Activity 2.5.6](https://teambasedinquirylearning.github.io/linear-algebra/2023/EV5.html#activity-53) and maybe elsewhere, the k hat is typeset differently than i hat and j hat.

What do you mean? I'm using `\hat \imath` ($\hat\imath$), `\hat \jmath` ($\hat\jmath$), and `\hat k` ($\hat k$). There is no `\hat \kmath` ($\hat \kmath$).

**Comment by siwelwerd** [comment]
The k is bigger than the i and j.  
![Screenshot 2023-10-03 at 10 55 20 AM](https://github.com/TeamBasedInquiryLearning/linear-algebra/assets/30658947/2cbb54fb-9eb2-4882-b808-3d8afa8b7ac8)

**Comment by StevenClontz** [comment]
I think we need to duke this out with more input. I'll cross-post to Slack and BlueSky.

**Comment by siwelwerd** [comment]
That's the only way to make such high stakes decisions for our book! 🤣

**Comment by StevenClontz** [comment]
Oh heck I'll get mathstodon on it as well. At least I can run a proper poll there.
