### ISSUE TITLE
Typos in EV5

### ISSUE THREAD

**Issue by jkostiuk** [TeamBasedInquiryLearning/linear-algebra#259]
2.5.1 (c), "Infinitely" many

Responses to 2.5.8 D should read "Fails to span and is linearly dependant" (I think Jared pointed this out on slack already, but when i searched EV5, i didn't see it.

**Comment by StevenClontz** [comment]
I think this stuff was caught here: https://github.com/TeamBasedInquiryLearning/linear-algebra/pull/258 But I should push a new build so it shows up in the 2024 preview edition online.

**Comment by siwelwerd** [comment]
Thanks! Make sure to remove the "is:open" tag in the search bar--the default is to only look through open issues, so it won't catch things like this that have been fixed (in this case, yesterday).

Jared's comments were copied to #257 , and I caught the "infinitely" in a2dff08, so yes, this was closed in #258.

**Comment by jkostiuk** [comment]
Got it—makes sense. Cheers,JordanOn Oct 4, 2023, at 12:15 PM, Drew Lewis ***@***.***> wrote:﻿
Thanks! Make sure to remove the "is:open" tag in the search bar--the default is to only look through open issues, so it won't catch things like this that have been fixed (in this case, yesterday).
Jared's comments were copied to #257 , and I caught the "infinitely" in a2dff08, so yes, this was closed in #258.
