### ISSUE TITLE
CheckIt vs Textbook mismatch in Module MX

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/linear-algebra#267]
The 2023 edition of the text has section [Section 4.2: The Inverse of a Matrix (MX2)](https://teambasedinquirylearning.github.io/linear-algebra/2023/MX2.html#MX2) but the [CheckIt 2023 problems for MX2](https://teambasedinquirylearning.github.io/linear-algebra/2024/exercises/#/bank/MX2/1/) are about "row operations as matrix multiplication" (which is MX4 in the 2023 and 2024 Early).

I think CheckIt MX1 and textbook MX1 are aligned.

I think [CheckIt MX2](https://teambasedinquirylearning.github.io/linear-algebra/2024/exercises/#/bank/MX2/1/) should align with [Textbook MX4](https://teambasedinquirylearning.github.io/linear-algebra/2023/MX4.html). 

I think [CheckIt MX3](https://teambasedinquirylearning.github.io/linear-algebra/2024/exercises/#/bank/MX3/1/) should align with [Textbook MX2](https://teambasedinquirylearning.github.io/linear-algebra/2024/MX2.html).

I think [CheckIt MX4](https://teambasedinquirylearning.github.io/linear-algebra/2024/exercises/#/bank/MX4/1/) should align with [Textbook MX3](https://teambasedinquirylearning.github.io/linear-algebra/2024/MX3.html).

It seems the easiest path would be to move around the CheckIt problem database numbering, since there are lots of places in the text that link to the (incorrect) Exercises, like this link: ([Exercises 4.2.4](https://teambasedinquirylearning.github.io/linear-algebra/2023/MX2.html#exercises-19) 
https://teambasedinquirylearning.github.io/linear-algebra/2023/MX2.html#exercises-19).

**Comment by siwelwerd** [comment]
I have a suspicion this is an oversight from @StevenClontz rearranging some things in the latest edition.  I think renaming the directories [here](https://github.com/TeamBasedInquiryLearning/linear-algebra/tree/main/exercises/outcomes/MX) to reflect the book will do what @owensks suggests, and then Steven will just need to redeploy the checkit website.

**Comment by StevenClontz** [comment]
Working on this..
