### ISSUE TITLE
EV7 Activity 2.7.8 suggestion from grad student

### ISSUE THREAD

**Issue by jkostiuk** [TeamBasedInquiryLearning/linear-algebra#273]
I had a grad student find the phrasing of this activity weird; they wrote:

"the phrasing in 2.7.8 is strange. "camera" is in quotes as if the term needed further interpretation, and a "level" is referred to as if we had immediately assumed the existence of a level. "environment" or "scene" would be more natural terms."

I wasn't personally confused by the wording, but it seems like a slight modification may help others?

Also: homogeneous is misspelled in (a).

**Comment by siwelwerd** [comment]
I agree with the student, I can guess as to what this activity is getting at but the video game context and wording just confuses me.  I think in general we need to be careful about applications where we are assuming some sort of cultural knowledge that we should not assume all of our students have.  I wonder if referring to something like a movie or TV show would be a little more universal way to get at a projection of R^3 onto R^2, and really does have a "camera" (no scare quotes needed).

**Comment by StevenClontz** [comment]
The difference is that a camera for a real-life movie or TV show doesn't actually use linear algebra (well, at least a film-based camera, I dunno about digital cameras).

I suggest we switch the video game reference with a computer-animated film instead, which a broader audience will have engaged with. You can't have an application without some assumption of prior knowledge from students, so instructors should facilitate as appropriate (I usually verbally tell students to think of Toy Story if they've never played Super Mario).

**Comment by StevenClontz** [comment]
Closed by #277
