### ISSUE TITLE
Ordering of stuff in Module MX

### ISSUE THREAD

**Issue by owensks** [TeamBasedInquiryLearning/linear-algebra#280]
[Activity 4.2.4](https://teambasedinquirylearning.github.io/linear-algebra/2023/MX2.html#activity-125) asks students to sort statements and it includes statements of the form $A\vec{x}=\vec{b}$. But since the Module MX was re-ordered, I think this Activity would make more sense if we moved it to MX3 (on matrix-vector products as a way to solve system of linear equations). I believe this is the very first instance of the matrix-vector equation $A\vec{x}=\vec{b}$ and this activity is conceptually rich, so if we keep it in this section, I think moving [Activity 4.2.5](https://teambasedinquirylearning.github.io/linear-algebra/2023/MX2.html#activity-126) before it, and perhaps adding another Activity about spanning $\mathbb{R}^m$ using a matrix-vector equation, before this one would be helpful.

Edit: Maybe it should follow directly after [Activity 4.3.3](https://teambasedinquirylearning.github.io/linear-algebra/2023/MX3.html#activity-132) .

**Comment by siwelwerd** [comment]
Looks like this was resolved by #302
