### ISSUE TITLE
EV3: Definition of subspace

### ISSUE THREAD

**Issue by jkostiuk** [TeamBasedInquiryLearning/linear-algebra#282]
My team and I had some challenges with the definition of subspace used this year--it really went against our own upbringing as: a subspace is a non-empty subset of the vector space that is closed under addition and scalar multiplication. 

I would really prefer to have what is Fact 2.3.3 be the definition at the beginning, and then have an activity and/or remark drawing attention to the fact that span(S) is always a subspace. 

Lastly, can we make the non-empty qualifier more visible and rework 2.3.7 so it reads more like "to show W is not a subspace, we can disprove one of these three things; if it's a subspace, we need to prove these three things"

This particular issue is causing a real stir for us in grading problem sets. Some facilitators have made this point more clear than others, and we found it hard to hammer the point home the way it was written in the activity book. as a result, we have many disgruntled students who lost points for not showing the zero vector was in some subspace we were working with in the problem set.

**Comment by StevenClontz** [comment]
Agreed on Remark 2.3.7, and #283 cleans that up alongside the similiar AT1 remark. Let me know your thoughts.

**Comment by StevenClontz** [comment]
I'm open to swapping Def 2.3.1 and Fact 2.3.3. Previously we defined a subspace to be a subset that's also a vector space - no good anymore now that we've punted vector spaces besides $\mathbb R^n$ to AT5.

I guess I thought Def 2.3.1 was better motivated for students new to vector spaces: students just learned what a span is, so now we're studying what the result of spanning is as an object, and calling that a subspace.

**Comment by jkostiuk** [comment]
I'd also be in favour of a deeper exploration. In EV2, students learn how to decide the answer to the question "Is span(S)=R^n?" and, notably, sometimes the answer is "no". 

So, something that I think would be well-motivated is "What properties are true about the sets span(S)?" and get them to discover that span(S) is (a) non-empty (even when S is empty); (b) closed under addition and (c) closed under multiplications. These seem like useful properties, and so it then makes sense to give a name to subsets that satisfy these important properties. 

Behind the scenes, we're basically having them discover that span(span(S))=span(S) and then we can also maybe close the section with the observation that span(W)=W whenever W is a subspace?

**Comment by siwelwerd** [comment]
Copying this over from the #315 discussion, where @jkostiuk proposed:

>  How about the following: let's work up to defining a Euclidean Subspace to be a subset of Euclidean vector that satisfies >(1) non-empty, (2) closed under sums, and (3) closed under scalar multiplication.
>
>Prior to making this definition, we can use the activity I wrote in this PR to have students see that Span(S) satisfies these >properties and then we can bring a modified version of the first activity of EV7 to EV3 that has students discover that >solutions to homogenous equations also enjoy these properities.
>
>Then, as a whole, the lesson is basically "here are two kinds of sets of vectors we work with a lot; they enjoy these three >properties, so we name it" and then if we use the name Euclidean subspace, then in AT5 we just drop euclidean (in the >same way we stop saying euclidean vector)?
>
>This would make EV3 a little longer, but I think it's time well spent if it's motivating the importance of subspace better.

I mentioned this to Jordan in conversation, but I would welcome a PR implementing this followed by feedback in the spring on how it went.  I'll leave this open until that PR is made, and go ahead and close out #315

**Comment by siwelwerd** [comment]
I believe this was closed by #336
