### ISSUE TITLE
Request for Synthesis Question in CheckIt for EV4, EV5, and EV6

### ISSUE THREAD

**Issue by sharonakrinsky** [TeamBasedInquiryLearning/linear-algebra#294]
I am looking to create some mastery check options in Linear Algebra and had an idea (actually - credit to my partner in crime Bosley for this one). 

Would it be possible to get a "synthesis" question that combines EV4, EV5 and EV6? I'm thinking of the following. 

Currently EV4 and EV5 both include three identical tasks. Then EV6 has one task for a basis. Could I get a version where it randomly selects ONE of the EV4 tasks, ONE of the EV5 tasks and then the EV6 task on a single question for a Canvas bank generation? I'm thinking of using it as the second time a student has to show mastery on these three standards after they have used the existing iteration of the questions for their first attempt.

If we don't want to build one for the main bank, I can do a custom one for myself, I just thought it might be interesting for more people than me, as it requires them to think about ALL the equivalent statements at once. Also - not sure if this is an "issue" or belongs somewhere else.

**Comment by siwelwerd** [comment]
I'm a little wary of putting too many extra things into the main bank.  But also, looking at https://teambasedinquirylearning.github.io/linear-algebra/2023/exercises/#/bank/Extra2Final/1/ , maybe you could just edit the template to get what is currently Tasks 2,3,4  will roughly suit your needs?

**Comment by sharonakrinsky** [comment]
I wasn't clear if I could edit the template and get it as the Canvas Bank export. I see how to do it for the PDF export, but does it work the same for the Canvas Bank export?

**Comment by StevenClontz** [comment]
As long as you edit the template and export without refreshing your browser in between, yes, the lms export gets your edits.

**Comment by StevenClontz** [comment]
I'm going to close this for now, but a related conversation on additional/alternative CheckIt outcomes has been opened here: https://github.com/TeamBasedInquiryLearning/linear-algebra/discussions/301
