### ISSUE TITLE
Suggestion for Activity 3.3.9

### ISSUE THREAD

**Issue by jkostiuk** [TeamBasedInquiryLearning/linear-algebra#295]
In some of our sections, students had some difficulties with this activity and I think the following suggestion might help us: can we turn this into a 2-parter with the first part being a MC question that's basically "Which of the following statements helps us decide if a given vector $\vec{w}$ is in the image of T?". I think something like this might help us better land the second part.

**Comment by StevenClontz** [comment]
Link to activity: [Activity 3.3.9](https://teambasedinquirylearning.github.io/linear-algebra/2023/AT3.html#activity-84)

**Comment by StevenClontz** [comment]
I agree that this needs better scaffolding and didn't land well in my class, though I'm not sure I follow your specific suggestion. Can you write out a full rough draft of your proposed revision?

**Comment by jkostiuk** [comment]
yes--i'll work on it on the plane on thursday
