### ISSUE TITLE
Mismatch between current version Checkit and Book

### ISSUE THREAD

**Issue by sharonakrinsky** [TeamBasedInquiryLearning/linear-algebra#296]
For 2023 edition, it looks like the MX module was reordered with the old MX2 becoming MX4, the old MX3 becoming MX2, and the old MX4 becoming MX3, but Checkit still has the old order. Can it be fixed?

**Comment by siwelwerd** [comment]
See #267.  I'm not sure if @StevenClontz has an easy way to change this in the 2023 edition. It is already fixed for the 2024 edition, for which there will be a Preview version available for the spring.

I am not sure how much the 2024 Checkit bank has changed already, so one workaround might just be to start using that: https://teambasedinquirylearning.github.io/linear-algebra/2024/exercises/#/bank/

**Comment by siwelwerd** [comment]
The downside to using the 2024 edition is that every now and then some bonehead will try to redeploy the book and forget to do the Checkit at the same time, and it will break.  But that hasn't happened in like a whole week now.

**Comment by StevenClontz** [comment]
We're a bit downstream to fix this for 2023 edition, but the fix is already made for a 2024 Early Edition release in a month or so.
