### ISSUE TITLE
Bug in AT5 exercises

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#305]
Dunno why I just now had a student point this out after a week or two, but I'm pretty sure the answer for Task 1 at https://teambasedinquirylearning.github.io/linear-algebra/2024/exercises/#/bank/AT5/1/ is wrong.

I believe this is an instance of variant 0 at https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/3b561e113070e75cddc8826e9a73a44cbec5d954/exercises/outcomes/AT/AT5/generator.sage#L27 Tagging @siwelwerd who wrote this code and may be able to diagnose quicker than I.

**Comment by siwelwerd** [comment]
Out of the office today but will get this sorted on Monday
