### ISSUE TITLE
Another AT5 bug...

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#307]
![image](https://github.com/TeamBasedInquiryLearning/linear-algebra/assets/1559632/b849f439-f976-40e0-9230-01bbf042a5ea)

But compare with https://sagecell.sagemath.org/?z=eJxtj8EKgzAMhu-C71A8tTYeEmQbgz2LSO3YYFPRurVvv7ZWt8MKbfiTP1_STl_ZMD6WmRsEQ-KcZ8wfi-CQXZjBpAkcBU2rnrRZpp5xbce277hFaUmSgKQdSkfyIESe5VkXRpj7U89cgdkngAu8v7gKsVSllbV_XfXFVvUp5vEYC4mvIG4L246vduKFYrZB5vy1DflIRfTOt-HN92XWj_PYLoBHgBCBuvpieXcnn4CfzNbxAaStWSY=&lang=sage&interacts=eJyLjgUAARUAuQ==

**Comment by StevenClontz** [comment]
Yeah, that's a great idea.

**Comment by siwelwerd** [comment]
@StevenClontz Any thoughts on performance impacts of that change?  Probably worth it regardless just to prevent bugs like this if/when additional cases are added.

**Comment by StevenClontz** [comment]
I think that it should be fine, and would help us create new scenarios quickly.

Right now I'm making a PR that inserts some `assert`s to try to figure out where to make a hotfix.

**Comment by siwelwerd** [comment]
I think the fix is to remove distv from here:
https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/1de0caf4131b99f21bef81094d3d4c4bbc22e894/exercises/outcomes/AT/AT5/generator.sage#L112

**Comment by StevenClontz** [comment]
So here's what I get from #308:

```
Exception: failed on dist_v (-5*c*x1 - 5*c*x2 + 2*c*y1 + 2*c*y2 + 4*c - 4, -24*c*x1 - 24*c*x2 + 9*c*y1 + 9*c*y2 + 12*c - 12) (-5*c*x1 - 5*c*x2 + 2*c*y1 + 2*c*y2 - 4, -24*c*x1 - 24*c*x2 + 9*c*y1 + 9*c*y2 - 12)
```

Looks like the same vector distribution bug. Working on a fix...

**Comment by StevenClontz** [comment]
> I think the fix is to remove distv from here:
> 
> https://github.com/TeamBasedInquiryLearning/linear-algebra/blob/1de0caf4131b99f21bef81094d3d4c4bbc22e894/exercises/outcomes/AT/AT5/generator.sage#L112

Yep, making that change passes all the assertions.

**Comment by siwelwerd** [comment]
This one is less bug, more human error (i.e. me adding dist_v to that list when that property actually fails)

**Comment by StevenClontz** [comment]
Fortunately, this doesn't show up in any of the 20 practice exercises, so I just need to apologize to the one student who got a bad quiz. 🤣

**Comment by siwelwerd** [comment]
Tell them the person responsible for the error no longer works at the university 😉
