### ISSUE TITLE
AT5 refactor

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#309]
As discussed in #307, we want to refactor AT5's generator to have Sage manually check the vector space properties rather than assert them manually. This will prevent bugs for slipping in, and make it easier to define new o-operations to add variety.

**Comment by siwelwerd** [comment]
Should also add some comments in the code to better document the process of creating examples while we are at it.

**Comment by StevenClontz** [comment]
Found another surprise (which I imagine will go away with the refactor):

[at least two properties fail](https://sagecell.sagemath.org/?z=eJx9UNFqwzAMfA_kH0SfrFiBWiMvhf1KS7EzOtjakqSZ9fe17DQwAhUI-6TzyafQf8Ht_vMYzexoZjzUFaSIjsTBJ8xuwUzCirngoZ8ewxVMH-_nazDR2chICxJnhdsOsa7qKuiA6fu3H42nedUnUbX_YgVpLELc-ONHI63b68X6Jrap1IjVAtKGX9hdJndY2vkTniBQGgpCag0kZbIExdN5MDsPASIIxJMDSRlPnE7e5efj5fZnVhNlXSavCMnk1SCq28LL7ZW98JA2Fdxq25C6JG_EtPmSWsn4BOWGeaE=&lang=sage&interacts=eJyLjgUAARUAuQ==)

But we're only suggesting one:

![image](https://github.com/TeamBasedInquiryLearning/linear-algebra/assets/1559632/6ab40a5e-985d-4c5d-bcdd-e37056971b88)
