### ISSUE TITLE
"non-Euclidean vector spaces"

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#319]
In [Remark 3.5.7](https://teambasedinquirylearning.github.io/linear-algebra/2023/AT5.html#remark-13), we say that the complex numbers are a 'non-Euclidean vector space'.  However, they are isomorphic to the Euclidean vector space $\mathbb{R}^2$.  I am not sure there is universal agreement that something can be isomorphic to a Euclidean vector space but not be a Euclidean vector space.

**Comment by StevenClontz** [comment]
Would you (or someone) say "Euclidean vector space" is a synonym for "finite-dimensional vector space"?

**Comment by siwelwerd** [comment]
They are isomorphic, so it feels a little weird to me to insist they are different.  

I think Euclidean carries some connotation that the base field is the real numbers though.  [Wikipedia](https://en.wikipedia.org/wiki/Euclidean_space#Technical_definition), citing Berger, defines Euclidean vector space as a finite dimensional real inner product space.  So I guess yes, someone does say they are synonyms.

**Comment by StevenClontz** [comment]
In any case, the intent here is that $\mathbb C$ is a vector space that isn't identical to $\mathbb R^n$, although eventually students will learn it's isomorphic to $\mathbb R^2$.

I think the clearest solution #323 is to just drop "non-Euclidean" and let the instructor make the point however they feel is appropriate.
