### ISSUE TITLE
(2024) Activity 1.2.2(b)(c)(d) typos

### ISSUE THREAD

**Issue by jbunn3** [TeamBasedInquiryLearning/linear-algebra#341]
(2024) Activity 1.2.2(b)(c)(d) has 3 at the end of the last equation in each instance instead of 6.

**Comment by siwelwerd** [comment]
Accidentally committed the fix for this to main, so 275932d closes this.

**Comment by StevenClontz** [comment]
@siwelwerd I've fixed the branch protection settings so even administrators cannot push to main directly by accident. (we can still make PRs and bypass the review process by self-merging).

**Comment by StevenClontz** [comment]
I did this for all three books.
