### ISSUE TITLE
(2024) Activity 1.2.5 typo?

### ISSUE THREAD

**Issue by jbunn3** [TeamBasedInquiryLearning/linear-algebra#343]
In (2024) Activity 1.2.5, the last augmented matrix has alterations to rows 2 and 3. R_3-1R_2->R_3 was applied, but row 2 was changed for some reason.

**Comment by siwelwerd** [comment]
Yeah, it is like that to match the previous activity.  And there are two row moves done there, but the prompt was changed to provide students with options now.  So maybe also need to change part (e) on [Activity 1.2.4](https://teambasedinquirylearning.github.io/linear-algebra/2024e/LE2.html#LE2-activity-sort) ?

**Comment by jbunn3** [comment]
You know, I didn't notice that those activities were matched up. Yeah, I would recommend changing the previous one too.
