### ISSUE TITLE
Language about above/below pivots still confusing

### ISSUE THREAD

**Issue by siwelwerd** [TeamBasedInquiryLearning/linear-algebra#350]
Some of @jkostiuk's facilitators noted the language in [Definition 1.2.6](https://teambasedinquirylearning.github.io/linear-algebra/2024e/LE2.html#definition-8) around zeroes above/below pivots is still confusing--e.g. does "above" mean immediately above, i.e. adjacent?.  This was recently modified in #242 , but apparently not sufficiently.

**Comment by StevenClontz** [comment]
"Every vertical column that includes a pivot has zeros filling every other position." ?

**Comment by StevenClontz** [comment]
"Every term in a vertical column including a pivot, besides the pivot itself, is 0."

**Comment by siwelwerd** [comment]
I wonder if instead of changing the definition, we could instead change the examples in [Activity 1.2.7](https://teambasedinquirylearning.github.io/linear-algebra/2024e/LE2.html#activity-7) and [Activity 1.2.8](https://teambasedinquirylearning.github.io/linear-algebra/2024e/LE2.html#activity-8) to highlight this.  That is, make sure there is a non-example with zeroes adjacent to the pivot, but a nonzero above or below (but non-adjacent).  We'd have to switch them all to $4 \times 4$, but maybe that's okay.

**Comment by StevenClontz** [comment]
¿Por qué no los dos?

**Comment by siwelwerd** [comment]
I think the existing language actually says exactly what it should, and in particular I like avoiding the use of row or column there in favor of above/below.  I think illustrating via an example will likely be sufficient to clarify this edge case without making the definition more confusing.

**Comment by jkostiuk** [comment]
I agree completely with the idea of using 4x4 matrices to illustrate and not actually modifying the language
