### ISSUE TITLE
LE2 1.2.5 

### ISSUE THREAD

**Issue by jkostiuk** [TeamBasedInquiryLearning/linear-algebra#354]
in activity 1.2.5, there are in fact multiple row operations performed in the last step. One option would be change the matrices and row operations a bit, but another might just be to add the row operations that are needed-- that is, perhaps, the activity can be worded in such a way that allows the possibility that multiple row operations may be needed.

**Comment by siwelwerd** [comment]
See #323, fixed in #324 . See [Activity 1.2.5](https://teambasedinquirylearning.github.io/linear-algebra/2024/LE2.html#activity-6) in the dev version.
