### ISSUE TITLE
Fact 3.3.11 might be misleading

### ISSUE THREAD

**Issue by jbunn3** [TeamBasedInquiryLearning/linear-algebra#360]
The final sentence in Fact 3.3.11 says: "Use the coefficients of its free variables to get a basis for the kernel." This is referring to the coefficients found after finding the solution set. Some students may interpret this as the coefficients from the original system, or even the coefficients from the RREF of the original augmented matrix. Maybe add in a reference to the solution set?

**Comment by siwelwerd** [comment]
I'm not sure if we want to change the language there, but maybe add in a reference back to [Fact 2.7.4](https://teambasedinquirylearning.github.io/linear-algebra/2024e/EV7.html#fact-10)?  Any language change that is coming to mind for me is cumbersome and will add confusion in other ways I think.  But feel free to propose some exact wording you think is better.

Could also add a reference back to [Observation 2.6.4](https://teambasedinquirylearning.github.io/linear-algebra/2024e/EV6.html#observation-9) in the second bullet point.

**Comment by jbunn3** [comment]
I like the idea of a reference, as I could see where trying to clarify the wording could make it overly cumbersome. Sent from my iPhoneOn Mar 15, 2024, at 11:25 AM, Drew Lewis ***@***.***> wrote:﻿
I'm not sure if we want to change the language there, but maybe add in a reference back to Fact 2.7.4?  Any language change that is coming to mind for me is cumbersome and will add confusion in other ways I think.  But feel free to propose some exact wording you think is better.
Could also add a reference back to Observation 2.6.4 in the second bullet point.

**Comment by siwelwerd** [comment]
Bonus feature of referencing is that clicking on them (in the HTML) expands into examples within Fact 3.3.11 there.

![image](https://github.com/TeamBasedInquiryLearning/linear-algebra/assets/30658947/80cce22a-f844-4b57-a956-e734265d9c01)
