### ISSUE TITLE
Multipart activities should be clearly indicated on slides.

### ISSUE THREAD

**Issue by StevenClontz** [TeamBasedInquiryLearning/linear-algebra#80]
Alternatively, we could add a header that communications that multiple parts follow. But in particular, there's one question in V that isn't clear that it has multiple parts that break it down, and generally I don't see a purpose of not displaying the first part of the question by default on slides.

**Comment by siwelwerd** [comment]
Not sure how much this will impact our thinking on this issue, but I've noticed that while I love multipart activities with pauses in between the parts in face-to-face classes, these aren't really helpful in synchronous online classes (it takes too long to get into and out of breakout rooms to not just say "do all the parts now").

**Comment by StevenClontz** [comment]
With the change to PreTeXt, the TBIL-LA project will ideally be able to shift to focus on authoring PreTeXt content, not its presentation.*

So this is now a consideration for me wearing a PreTeXt hat: when building slides, how should an <activity> with many <parts> be displayed? This should be reasonable regardless of how the activity was authored. Likely it should be configurable by the "publisher" (display all parts at once, or iterate one at a time).

* I'm assuming here that PreTeXt has the functionality we need to facilitate TBIL, or will accept PRs to add this functionality (true so far).

**Comment by siwelwerd** [comment]
Closing this as made redundant by #255
